version: '3'

# service description
services:

  # watchtower service
  xmr-miner:
    image: ghcr.io/jonas-merkle/container-xmr-mining:master
    #build:
    #  context: ./src
    #  dockerfile: ./Dockerfile
    container_name: xmr-miner
    hostname: xmr-miner
    restart: unless-stopped
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "3.0"   # max cpu usage (1.0 equals 1 cpu core) 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/miner-config:ro
    labels:
      # enbale watchtower updates
      - "com.centurylinklabs.watchtower.enable=true"