name: Build and Publish Docker Image

on:
  # Run the workflow once a week (on Sunday at midnight UTC)
  schedule:
    - cron: '0 0 * * 0'

  # Trigger the workflow when a new tag is pushed, matching version-*.*
  push:
    tags:
      - 'version-*.*.*'
    branches:
      - main

  # Allow the workflow to be triggered manually
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to GitHub's Docker Registry
      - name: Log in to GitHub Docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Set up Docker Buildx for multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push the Docker image
      - name: Build and Push Docker image
        run: |
          # Set image tag based on the context (cron, push, or manual dispatch)
          if [ "${{ github.event_name }}" == "push" ]; then
            IMAGE_TAG="${{ github.ref_name }}"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            IMAGE_TAG="latest"
          else
            IMAGE_TAG="latest"
          fi

          # Change to the src directory
          cd src

          # Build and push the image
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --file ./Dockerfile \
            --tag ghcr.io/${{ github.repository }}/container-xmr-mining:$IMAGE_TAG .

    # Only run on push, schedule, or manual dispatch
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
